[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_calculator = "7oU3XEDPr3MYrPfL5rWGYfeevAnQMRXh5um6nBtpA1Hs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/alexandru/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
